(deftheme nle-railscasts
  "Created 2017-02-13.")

(custom-theme-set-faces
 'nle-railscasts
 '(default ((t (:family "Ubuntu Mono" :foundry "nil" :width normal :height 180 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "grey80" :background "#232323" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#FFFFFF" :background "orange"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "museo sans"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#FF6600" :inherit (bold)))))
 '(highlight ((t (:foreground "#b2b2b2" :background "black"))))
 '(region ((t (:foreground "white" :background "#555577"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "DarkSlateBlue"))))
 '(trailing-whitespace ((t (:background "#2aa1ae"))))
 '(font-lock-builtin-face ((t (:foreground "#C8C8FF"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#BC9458"))))
 '(font-lock-comment-face ((t (:foreground "#BC9458" :background "#292e34"))))
 '(font-lock-constant-face ((t (:foreground "#6D9CBE"))))
 '(font-lock-doc-face ((t (:foreground "#2aa1ae"))))
 '(font-lock-function-name-face ((t (:foreground "#FFC66D" :inherit (bold)))))
 '(font-lock-keyword-face ((t (:foreground "#CC7833" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#A5C261"))))
 '(font-lock-type-face ((t (:foreground "#6D9CBE" :inherit (bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#C8C8FF"))))
 '(font-lock-warning-face ((t (:foreground "Pink" :background "#292b2e"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#2aa1ae"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#c56ec3"))))
 '(fringe ((t (:foreground "#b2b2b2" :background "#232323"))))
 '(header-line ((t (:height 0.3))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#b2b2b2" :background "#5e5079"))))
 '(mode-line ((t (:box nil :foreground "black" :inherit (powerline-active1)))))
 '(mode-line-buffer-id ((t (:inherit (mode-line)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#b2b2b2" :inherit (powerline-inactive1)))))
 '(isearch ((t (:foreground "#333333" :background "#22EEEE"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight normal :foreground "#333333" :background "#f6e05c"))))
 '(match ((t (:foreground "#86dc2f" :background "#444155"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'nle-railscasts)
