(deftheme nle-tomorrow-day
  "Created 2015-04-20.")

(custom-theme-set-variables
 'nle-tomorrow-day
 '(ansi-color-names-vector ["#4d4d4c" "#c82829" "#718c00" "#eab700" "#4271ae" "#8959a8" "#3e999f" "#ffffff"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'nle-tomorrow-day
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#8959a8"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8e908c" :slant italic))))

 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#f5871f" :background "#F4F0EB" :slant italic))))

 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#3e999f"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#4271ae"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#3e999f"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#c82829"))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "royal blue"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#8959a8"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :foreground "#f5871f" :height 1.44))))
 '(helm-selection ((((class color) (min-colors 89))  (:foreground "black" :background "green"))))
 '(helm-selection-line ((((class color) (min-colors 89))  (:foreground "black" :background "green"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#8959a8"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#4271ae" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#8e908c"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "black" :background "grey90" :height 0.9))))
 '(org-block-background ((t (:background "grey90"))))
 '(org-block-begin-line ((t (:foreground "grey20" :background "grey60" :height 0.8))))
 '(org-block-end-line ((t (:foreground "grey20" :background "grey60" :height 0.8))))
 '(org-code ((t (:foreground "#eab700"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#d6d6d6"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#4271ae" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#3e999f"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#f5871f" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#8e908c"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#3e999f"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#c82829"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ffffff"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#4271ae" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#f5871f"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#f5871f"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#8959a8"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#c82829"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#f5871f"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#c82829"))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link :underline nil))))
 '(markdown-reference-face ((((class color) (min-colors 89)) (:foreground "#718c00" :weight bold :underline nil :height 0.9))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#718c00" :weight bold :underline nil :height 0.9))))
 '(markdown-footnote-face ((((class color) (min-colors 89)) (:foreground "#718c00" :weight bold :underline nil :height 0.9))))
 '(hl-line ((((class color) (min-colors 89)) (:foreground nil  :background "pale goldenrod" ))))
 '(region ((((class color) (min-colors 89)) (:foreground nil  :background "slategray1" ))))

 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:foreground "#4271ae" :weight bold :underline nil :height 1.1))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#4271ae" :weight demibold))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8959a8" :weight bold))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#3e999f"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#eab700"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#f5871f"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#4271ae"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8959a8"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#3e999f"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#4271ae"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#4271ae"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#718c00"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#F4F0EB"))))
 '(org-indent ((((class color) (min-colors 89)) (:background "#F4F0EB" :foreground "F4F0EB"))))
 '(default ((((class color) (min-colors 89)) (:foreground "grey13" :background "#F4F0EB")))))



(provide-theme 'nle-tomorrow-day)
